### ISSUE TITLE
Forest Guardian don't have any buff.

### ISSUE THREAD

**Issue by Adeuxline** [Crypto2557/Crypto2557.github.io#31]
5-Star 10%, 6-Star 30%.

See the pet here : [Leo](http://endlessfrontierdata.com/pets/26)

**Comment by Crypto2557** [comment]
Because you need zero units before you have the pet no progress bar is shown. Because you would never intentionally add one of these units to your team just for the offline marching buff. 
However, if you 5* the pet the progress bar for the buff is shown as intended.
![image](https://user-images.githubusercontent.com/24509495/51406282-ef74ec00-1b58-11e9-9bb1-be8bef636f55.png)

**Comment by Adeuxline** [comment]
Crap you're right. I add all pets yesterday but one didn't save.
